version: "3.9"
name: docker-compose-lamp
services:
  # fontend:
  #   build: ./fontend/
  #   container_name: fontend_nextjs
  #   image: node:latest
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./fontend/:/var/www/html
  #   depends_on:
  #     - db_mysql
  #   environment:
  #     DB_HOST: db
  #     DB_USER: skz
  #     DB_PASSWORD: Skzqqwwee44$$
  #     DB_NAME: db_mysql
  #   networks:
  #     - mynetwork
  backend:
    container_name: backend_nodejs
    build: ./backend/
    image: node:latest
    restart: always
    ports:
      - "7777:7777"
    volumes:
      - ./backend/:/app_backend
    working_dir: /app_backend
    depends_on:
      - redis-server
    environment:
      - NODE_ENV= development
    command: npm run start

    links:
      - redis-server
      - mysql
    networks:
      mysqlnetwork:
        ipv4_address: 192.168.65.7

  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    ports:
      - "5555:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    # mem_limit: 512m

    environment:
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=skz
      - MYSQL_PASSWORD=skzz
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    networks:
      mysqlnetwork:
        ipv4_address: 192.168.65.5

  mysql-admin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: mysql-admin
    ports:
      - "4444:80"
    mem_limit: 512m
    depends_on:
      - mysql
    environment:
      - PMA_HOST=192.168.65.5
      - PMA_PORT=3306
      - PMA_USER=skz
      - PMA_PASSWORD=skzz
      - PMA_ROOT_PASSWORD=my-secret-pw
      - PMA_ARBITRARY=1
      - PMA_DATABASE=app_db
    networks:
      mysqlnetwork:

  redis-server:
    restart: always
    image: redis
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "3333:6379"
    volumes:
      - ./redis:/data
    mem_limit: 96m
    networks:
      mysqlnetwork:
        ipv4_address: 192.168.65.3

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "2222:2222"
    volumes:
      - ./src/:/var/www/html
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      mysqlnetwork:
        ipv4_address: 192.168.65.2
networks:
  mysqlnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.65.0/24
          gateway: 192.168.65.1
